steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/health-ai-app-image:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/health-ai-app-image:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'health-ai-app-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/health-ai-app-image:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'PORT=8080'

images:
- 'gcr.io/$PROJECT_ID/health-ai-app-image:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY